固件升级脚本中添加对版本的判断，如果要升级的版本比已有固件版本低，则终止升级过程。

diff --git a/rootfs_scripts/rootfs/sbin/fw-upgrade b/rootfs_scripts/rootfs/sbin/fw-upgrade
--- a/rootfs_scripts/rootfs/sbin/fw-upgrade
+++ b/rootfs_scripts/rootfs/sbin/fw-upgrade
@@ -38,10 +38,65 @@ if ! [ -f "${fw_file}" ]; then
   exit 1
 fi
 
+check_version() {
+  if [ -z $1 ]; then
+    warn "unknown new firmware version."
+    return 1;
+  fi
+
+  old_ver=$(sqlite3 /data/configuration.sqlite3 \
+          "select value from base_info where name=\"firmware\"")
+  if [ -z $old_ver ]; then
+    warn "can not get old firmware version."
+    return 1;
+  fi
+
+  old_major=$(echo $old_ver | awk -F. '{print $1}')
+  old_minor=$(echo $old_ver | awk -F. '{print $2}')
+  old_revsion=$(echo $old_ver | awk -F. '{print $3}')
+
+  new_major=$(echo $1 | awk -F. '{print $1}')
+  new_minor=$(echo $1 | awk -F. '{print $2}')
+  new_revsion=$(echo $1 | awk -F. '{print $3}')
+
+  if [ -z $old_major -o \
+       -z $old_minor -o \
+       -z $old_revsion -o \
+       -z $new_major -o \
+       -z $new_minor -o \
+       -z $new_revsion ]; then
+    warn “bad format of version.”
+    return 1
+  fi
+
+  if [ $new_major -gt $old_major ]; then
+    return 0
+  fi
+  if [ $new_minor -gt $old_minor ]; then
+    return 0
+  fi
+  if [ $new_revsion -gt $old_revsion ]; then
+    return 0
+  fi
+
+  return 1
+}
+
 ## extract the firmware
+echo 2 > $lock_file
 echo -e "\033[1mExtracting the firmware...\033[0m"
-if ! fw_decode -d ${fw_dir}/files ${fw_file}; then
+new_ver=$(fw_decode -d ${fw_dir}/files ${fw_file} \
+        | grep 'Version' \
+        | awk '{print $2}')
+if [ $? -ne 0 ]; then
+  echo 0 > $lock_file
   fatal "Extract firmware failed"
+  exit 1
+fi
+
+if ! check_version $new_ver; then
+  echo 0 > $lock_file
+  fatal "Check version failed"
   exit 1
 fi
 
@@ -75,6 +130,7 @@ EOF
   return 0
 }
 
+echo 3 > $lock_file
 ## program every partition
 for f in $(ls ${fw_dir}/files); do
   if ! get_mtddev_from_name $f; then
@@ -90,6 +146,8 @@ for f in $(ls ${fw_dir}/files); do
   fi
 done
 
+sqlite3 /data/configuration.sqlite3 "update base_info set value=\"$new_ver\" where name=\"firmware\""
+echo 4 > $lock_file
 ## program OK, reboot the system.
 echo -e "\033[32;1mUpgrade complete, now rebooting system...\033[0m"
 sleep 1
